apiVersion: apps/v1
kind: Deployment
metadata:
  name: scp-operator
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels: { app: scp-operator }
  template:
    metadata:
      labels: { app: scp-operator }
    spec:
      serviceAccountName: scp-operator
      containers:
        - name: operator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:MaxRAMPercentage=75"
